- hosts: all
  become: true
  tasks: 
     - name: delete old deployment
       command: sudo kubectl delete -f /home/ec2-user/Deployment.yml
     - name: delete old service
       command: sudo kubectl delete -f /home/ec2-user/Service.yml
     - name: create new deployment
       command: sudo kubectl apply -f /home/ec2-user/Deployment.yml
     - name: create new service
       command: sudo kubectl apply -f /home/ec2-user/Service.yml