apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpweb
  template:
    metadata:
      labels:
        app: phpweb
    spec:
      containers:
        - name: my-container
          image: tunat/phpweb:latest 