kind: Deployment
apiVersion: apps/v1
metadata:
  name: phpweb-deploy
  labels:
    app: phpweb-deploy-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpweb
  template:
    metadata:
      labels:
        app: phpweb
    spec:
      containers:
      - name: phpweb
        image: tunat/phpweb:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
