kind: Deployment
apiVersion: apps/v1
metadata:
   name: phpweb
spec:
   replicas: 1
   selector:   
    matchLabels:
     app: phpweb
   template:
      metadata:
        labels:
          app: phpweb
      spec:
       containers:
        - name: my-container
          image: tunat/phpweb:latest 
          imagePullPolicy: Always
          ports:
          - containerPort: 80