kind: Service                             
apiVersion: v1
metadata:
  name: phpweb
  labels:
    app: phpweb
spec:
  ports:
    - port: 8080                               
      targetPort: 80                    
      nodePort: 31200
  selector:
    app: phpweb                    
  type: LoadBalancer                   